services:
  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  backend:
    image: python:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: sh -c "pip install -r requirements.txt && WORKHUB_MYSQL_USER=workhub_user WORKHUB_MYSQL_PWD=WHC_123_2024 WORKHUB_MYSQL_HOST=db WORKHUB_MYSQL_DB=workhubconnect_db python3 -m api.v1.app"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workhubconnect_db
      MYSQL_USER: workhub_user
      MYSQL_PASSWORD: WHC_123_2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # - ./backend/sql_dumps:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootpassword",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: workhub_user
      PMA_PASSWORD: WHC_123_2024
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
